variables:
  # The domain used for the live deploy_prodment
  KUBE_NAMESPACE_dev: dev
  KUBE_NAMESPACE_qa: qa
  KUBE_NAMESPACE_staging: staging
  KUBE_NAMESPACE_prod: prod
  IP_DEV: 54.217.94.203 #Remplacer par votre IP de la VM
  IP_STAGING: 54.217.94.203 #Remplacer par votre IP de la VM
  IP_PROD: 54.217.94.203 #Remplacer par votre IP de la VM
  NODEPORT_DEV: 30000
  NODEPORT_STAGING: 30001
  NODEPORT_PROD: 30002
  S_GATEWAY: gateway
  S_ORDERS: orders
  S_USERS: users

stages:
  - test
  - build
  - push
  - deploy_dev
  - deploy_QA
  - deploy_staging
  - deploy_prod

test:
  stage: test
  script:
    - uname -a

build:
  stage: build
  script:
    # Build the container image
    - docker build -t "$CI_REGISTRY_IMAGE/$S_GATEWAY:latest" ./gateway/
    - docker build -t "$CI_REGISTRY_IMAGE/$S_ORDERS:latest" ./orders/
    - docker build -t "$CI_REGISTRY_IMAGE/$S_USERS:latest" ./users/

    # Tag the container image from latest to the commit ref
    - docker tag "$CI_REGISTRY_IMAGE/$S_GATEWAY:latest" "$CI_REGISTRY_IMAGE/$S_GATEWAY:$CI_COMMIT_SHORT_SHA"
    - docker tag "$CI_REGISTRY_IMAGE/$S_ORDERS:latest" "$CI_REGISTRY_IMAGE/$S_ORDERS:$CI_COMMIT_SHORT_SHA"
    - docker tag "$CI_REGISTRY_IMAGE/$S_USERS:latest" "$CI_REGISTRY_IMAGE/$S_USERS:$CI_COMMIT_SHORT_SHA"

push:
  stage: push
  before_script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker push "$CI_REGISTRY_IMAGE/$S_GATEWAY:$CI_COMMIT_SHORT_SHA"
    - docker push "$CI_REGISTRY_IMAGE/$S_ORDERS:$CI_COMMIT_SHORT_SHA"
    - docker push "$CI_REGISTRY_IMAGE/$S_USERS:$CI_COMMIT_SHORT_SHA"
    - if [ ! -z "$CI_COMMIT_TAG" ]; then
        docker push "$CI_REGISTRY_IMAGE/$S_GATEWAY:latest";
        docker push "$CI_REGISTRY_IMAGE/$S_ORDERS:latest";
        docker push "$CI_REGISTRY_IMAGE/$S_USERS:latest";
      fi

deploy_dev:
  stage: deploy_dev
  script:
    - rm -Rf .kube
    - mkdir .kube
    - ls
    - cat $KUBE_CONFIG > .kube/config
    - cp Appexam/values.yaml values.yml
    - cat values.yml
    - sed -i "s|jaobed/gatway_image:v.00|$CI_REGISTRY_IMAGE/$S_GATEWAY:$CI_COMMIT_SHORT_SHA|g" values.yml
    - sed -i "s|jaobed/orders_image:v.00|$CI_REGISTRY_IMAGE/$S_ORDERS:$CI_COMMIT_SHORT_SHA|g" values.yml
    - sed -i "s|jaobed/users_image:v.00|$CI_REGISTRY_IMAGE/$S_USERS:$CI_COMMIT_SHORT_SHA|g" values.yml
    - cat values.yml

    - sudo helm upgrade --install app Appexam/ --values=values.yml --namespace $KUBE_NAMESPACE_dev


deploy_QA:
  stage: deploy_QA
  script:
    - rm -Rf .kube
    - mkdir .kube
    - ls
    - cat $KUBE_CONFIG > .kube/config
    - cp Appexam/valuesqa.yaml values.yml
    - cat values.yml
    - sed -i "s|jaobed/gatway_image:v.00|$CI_REGISTRY_IMAGE/$S_GATEWAY:$CI_COMMIT_SHORT_SHA|g" values.yml
    - sed -i "s|jaobed/orders_image:v.00|$CI_REGISTRY_IMAGE/$S_ORDERS:$CI_COMMIT_SHORT_SHA|g" values.yml
    - sed -i "s|jaobed/users_image:v.00|$CI_REGISTRY_IMAGE/$S_USERS:$CI_COMMIT_SHORT_SHA|g" values.yml
    - cat values.yml
    - sudo helm upgrade --install app Appexam/ --values=values.yml --namespace $KUBE_NAMESPACE_qa

deploy_staging:
  stage: deploy_staging
  script:
    - rm -Rf .kube
    - mkdir .kube
    - ls
    - cat $KUBE_CONFIG > .kube/config
    - cp Appexam/valuesstaging.yaml values.yml
    - cat values.yml
    - sed -i "s|jaobed/gatway_image:v.00|$CI_REGISTRY_IMAGE/$S_GATEWAY:$CI_COMMIT_SHORT_SHA|g" values.yml
    - sed -i "s|jaobed/orders_image:v.00|$CI_REGISTRY_IMAGE/$S_ORDERS:$CI_COMMIT_SHORT_SHA|g" values.yml
    - sed -i "s|jaobed/users_image:v.00|$CI_REGISTRY_IMAGE/$S_USERS:$CI_COMMIT_SHORT_SHA|g" values.yml
    - cat values.yml
    - sudo helm upgrade --install app Appexam/ --values=values.yml --namespace $KUBE_NAMESPACE_staging


deploy_prod:
  stage: deploy_prod
  script:
    - rm -Rf .kube
    - mkdir .kube
    - ls
    - cat $KUBE_CONFIG > .kube/config
    - cp Appexam/valuesprod.yaml values.yml
    - cat values.yml
    - sed -i "s|jaobed/gatway_image:v.00|$CI_REGISTRY_IMAGE/$S_GATEWAY:$CI_COMMIT_SHORT_SHA|g" values.yml
    - sed -i "s|jaobed/orders_image:v.00|$CI_REGISTRY_IMAGE/$S_ORDERS:$CI_COMMIT_SHORT_SHA|g" values.yml
    - sed -i "s|jaobed/users_image:v.00|$CI_REGISTRY_IMAGE/$S_USERS:$CI_COMMIT_SHORT_SHA|g" values.yml
    - cat values.yml
    - sudo helm upgrade --install app Appexam/ --values=values.yml --namespace $KUBE_NAMESPACE_prod
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
      when: manual
